language: node_js
node_js:
  - "stable"
script:
  - npm test

after_success:
  -npm run coveralls

  services:
    -postgresql

  before_script:
  - psql -c 'CREATE DATABASE questionertest;' -U postgres
    - npm install --save-dev coveralls
  - npm install --save-dev nyc
